name: Build frontend

on:
  push:
    branches: 
      - main
      - dev-2

job:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Linting
        run: yarn run lint

      - name: Format
        run: yarn format
